### PR TITLE
Fix traceroute commands

### PR DESCRIPTION
**Pull request by SohKa**
Hello !

At the end of the cube installation, at the `MONITORING_IP` step, the `hypercube.sh` script can't execute the traceroute commands : 
```
TRACEROUTE 2XXX:XXXX:XXXX:XXXX::XXXX
=================
/usr/local/bin/hypercube.sh: line 505: traceroute6: command not found

TRACEROUTE 91.XXX.XXX.XXX
=================
/usr/local/bin/hypercube.sh: line 509: traceroute: command not found
```

Originally, I think the traceroute commands were provided by the `net-tools` package. As it's no longer the case, it is necessary to install the `traceroute` package (for the `traceroute` and `traceroute6` commands).

### CODE REVIEW

**Comment by keomabrun** [comment]
LGTM!

**Comment by keomabrun** [comment]
Thanks !

**Comment by SohKa** [comment]
np :)

**Comment by keomabrun** [comment]
@SohKa Note that the build script will soon be deprecated as images will be built automatically using https://github.com/YunoHost/arm-images :+1:

**Comment by SohKa** [comment]
@keomabrun Uh, I may have vaguely heard of it. What does that mean concretely ? Do you know a documentation to which I can refer to ?

**Comment by keomabrun** [comment]
@SohKa , this is not yet published and documented. You can join us on Mumble at 7pm the second Monday of each month if you'd like :) https://wiki.ldn-fai.net/wiki/Mumble

**Comment by SohKa** [comment]
Ok, I'll try to join. :)

**Pull request merged**
